version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # In case you need a tool for the database
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
volumes:
  sqlserver_data:
    driver: local
